title: Alias's Blog
description: 每天都要加油鸭，芳芳~
show_downloads: true

baseurl: "/Alias" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://higwendolyn.github.io" # change this to the base hostname & protocol for your site


google_analytics:

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: Alias
image: /thumbnail-jumbo.png

github:
  owner_url: "https://github.com/higwendolyn/Alias"

plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow

header_page_refs: ['now', 'about', 'contact']
